#!/usr/bin/env python3
"""Build per-model fitness profiles from battery captures.

Walks tests/integration/fixtures/probed/<model>/<scenario>/<path__mode>/
metadata.json files, aggregates by model + category, scores each
scenario class as pass/incomplete/fail/error, and emits a human-readable
fitness report.

Output: tests/integration/fixtures/probed/_fitness_report.md +
        tests/integration/fixtures/probed/_fitness_report.json

Usage:
    python scripts/analyze_probe_fitness.py [--model M] [--category C]
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PROBED_ROOT = REPO_ROOT / "tests" / "integration" / "fixtures" / "probed"
BATTERY_PATH = REPO_ROOT / "tests" / "integration" / "probes" / "battery.json"


def _scenario_category_map() -> dict[str, str]:
    if not BATTERY_PATH.exists():
        return {}
    battery = json.loads(BATTERY_PATH.read_text())
    out: dict[str, str] = {}
    for cat in ("generic", "codex", "noteapp", "format", "stress", "multimodal"):
        for s in battery.get(cat, []):
            out[s["id"]] = cat
    return out


def _classify(metadata: dict) -> str:
    """Map a probe metadata blob into a coarse outcome bucket.

    Returns one of: pass | incomplete | fail | error | skipped.
      pass        — HTTP 200 + finish_reason in {stop, completed, tool_calls}
      incomplete  — HTTP 200 + finish_reason in {incomplete, length} (budget-bound)
      fail        — HTTP >=400 (request rejected)
      error       — runtime error reading capture or building request
      skipped     — captured a "skipped" marker (e.g. unsupported path)
    """
    if "error" in metadata and metadata["error"]:
        return "error"
    if "skipped_reason" in metadata and metadata["skipped_reason"]:
        return "skipped"
    status = metadata.get("http_status")
    if not isinstance(status, int):
        return "error"
    if status >= 400:
        return "fail"
    finish = (metadata.get("finish_reason") or "").lower()
    if finish in ("stop", "completed", "tool_calls"):
        return "pass"
    if finish in ("incomplete", "length"):
        return "incomplete"
    return "pass"  # default to pass if status==200 and reason absent


def collect(model: str | None = None) -> dict[str, list[dict]]:
    """Walk capture tree; return {model: [metadata, ...]}."""
    out: dict[str, list[dict]] = defaultdict(list)
    if not PROBED_ROOT.exists():
        return out
    for model_dir in sorted(PROBED_ROOT.iterdir()):
        if not model_dir.is_dir() or model_dir.name.startswith("_"):
            continue
        m = model_dir.name
        if model and m != model:
            continue
        for scen_dir in sorted(model_dir.iterdir()):
            if not scen_dir.is_dir():
                continue
            sid = scen_dir.name
            for path_mode_dir in sorted(scen_dir.iterdir()):
                if not path_mode_dir.is_dir():
                    # Older captures put files at the scenario level directly.
                    # Handle the legacy layout by treating the scenario dir
                    # itself as one capture.
                    continue
                meta_file = path_mode_dir / "metadata.json"
                if not meta_file.exists():
                    continue
                try:
                    meta = json.loads(meta_file.read_text())
                except json.JSONDecodeError:
                    continue
                # Ensure key fields are present even if the runner
                # didn't write them.
                meta.setdefault("scenario_id", sid)
                meta.setdefault("model", m)
                out[m].append(meta)
    return out


def aggregate_by_model_and_category(
    captures: dict[str, list[dict]],
) -> dict[str, dict[str, dict[str, int]]]:
    cats = _scenario_category_map()
    out: dict[str, dict[str, dict[str, int]]] = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))
    for model, metas in captures.items():
        for meta in metas:
            sid = meta.get("scenario_id", "?")
            cat = cats.get(sid, "?")
            outcome = _classify(meta)
            out[model][cat][outcome] += 1
            out[model]["_total"][outcome] += 1
    return out


def render_markdown(
    aggregates: dict[str, dict[str, dict[str, int]]],
    captures: dict[str, list[dict]],
) -> str:
    lines: list[str] = []
    lines.append("# Per-model fitness profile\n")
    lines.append(
        "Generated by `scripts/analyze_probe_fitness.py` from capture metadata under "
        "`tests/integration/fixtures/probed/`. Coarse outcome buckets:\n"
    )
    lines.append("- `pass` — HTTP 200, finish_reason in {stop, completed, tool_calls}.")
    lines.append(
        "- `incomplete` — HTTP 200 but finish_reason in {incomplete, length}; "
        "the model didn't terminate naturally (budget-bound or thinking-budget-eaten)."
    )
    lines.append("- `fail` — HTTP >= 400. Request rejected upstream.")
    lines.append("- `error` — runtime error in the probe runner itself.")
    lines.append("- `skipped` — probe declined to run (e.g. unsupported path for this model).\n")
    lines.append("## Summary table\n")
    lines.append("| Model | pass | incomplete | fail | error | skipped |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for model in sorted(aggregates.keys()):
        t = aggregates[model]["_total"]
        lines.append(
            f"| `{model}` | {t.get('pass', 0)} | {t.get('incomplete', 0)} | "
            f"{t.get('fail', 0)} | {t.get('error', 0)} | {t.get('skipped', 0)} |"
        )
    lines.append("")
    lines.append("## Per-category breakdown\n")
    for model in sorted(aggregates.keys()):
        lines.append(f"### `{model}`\n")
        lines.append("| Category | pass | incomplete | fail | error | skipped |")
        lines.append("|---|---:|---:|---:|---:|---:|")
        for cat in ("generic", "codex", "noteapp", "format", "stress", "multimodal"):
            row = aggregates[model].get(cat, {})
            if not row:
                continue
            lines.append(
                f"| {cat} | {row.get('pass', 0)} | {row.get('incomplete', 0)} | "
                f"{row.get('fail', 0)} | {row.get('error', 0)} | {row.get('skipped', 0)} |"
            )
        lines.append("")
    lines.append("## Tool-call propensity\n")
    lines.append("How often each model emitted `tool_calls` (regardless of whether tools were required).\n")
    lines.append("| Model | tool_calls fires |")
    lines.append("|---|---:|")
    for model in sorted(captures.keys()):
        n = sum(1 for m in captures[model] if m.get("tool_calls_present"))
        lines.append(f"| `{model}` | {n} |")
    lines.append("")
    lines.append("## Latency overview (non-stream only)\n")
    lines.append("| Model | runs | mean ms | min ms | max ms |")
    lines.append("|---|---:|---:|---:|---:|")
    for model in sorted(captures.keys()):
        lats = [
            m["latency_ms"]
            for m in captures[model]
            if m.get("mode") == "non_stream" and isinstance(m.get("latency_ms"), int) and m.get("http_status") == 200
        ]
        if not lats:
            continue
        mean = sum(lats) // len(lats)
        lines.append(f"| `{model}` | {len(lats)} | {mean} | {min(lats)} | {max(lats)} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--model", default=None)
    args = p.parse_args()

    captures = collect(model=args.model)
    if not captures:
        print("no captures found under", PROBED_ROOT)
        return 1
    aggregates = aggregate_by_model_and_category(captures)
    md = render_markdown(aggregates, captures)
    out_md = PROBED_ROOT / "_fitness_report.md"
    out_md.write_text(md)
    out_json = PROBED_ROOT / "_fitness_report.json"
    out_json.write_text(
        json.dumps(
            {
                "aggregates": {
                    m: {cat: dict(buckets) for cat, buckets in cats.items()} for m, cats in aggregates.items()
                },
            },
            indent=2,
        )
    )
    print(f"Wrote {out_md}")
    print(f"Wrote {out_json}")
    print()
    print(md[:4000])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
